# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_LNET) += lnet.o

lnet-y := api-ni.o config.o nidstrings.o net_fault.o udsp.o	\
	  lib-me.o lib-msg.o lib-md.o lib-ptl.o			\
	  lib-socket.o lib-move.o module.o lo.o			\
	  router.o router_proc.o acceptor.o peer.o
